### ISSUE TITLE
GPS Driver in ROS

### ISSUE THREAD

**Issue by naterpotatoers** [naterpotatoers/Splot#15]
Adrien had one in Python
But we need a ROS a driver

**Comment by wwilliamcook** [comment]
ROS2 node that grabs GPS data from adafruit-circuitpython-gps library and publishes it in the correct format on a topic. See [REP 105](https://www.ros.org/reps/rep-0105.html) for ROS transform naming conventions, the [noetic robot_localization docs](https://docs.ros.org/en/noetic/api/robot_localization/html/index.html), and [this ROSCON robot_localization talk](https://vimeo.com/142624091). Although there only appears to be documentation for noetic (ROS1), the repo's default branch is `ros2` and it appears to be targeted at the colcon build system.
